# Generated by Django 3.0.3 on 2020-02-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='desired_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
